### ISSUE TITLE
4.08 release?

### ISSUE THREAD

**Issue by ygrek** [camlp4/camlp4#151]
latest available in opam is 4.07

Are there some blocking issues?

**Comment by XVilka** [comment]
See also https://github.com/ocaml/camlp4/pull/138

**Comment by glondu** [comment]
In Debian, this is blocking (at least): oasis -> ocaml-data-notation -> type-conv

**Comment by ghost** [comment]
Yep, we'll prepare a 4.08 release.

I have also started a thread with other OCaml developers to discuss what we are going to do about Camlp4. i.e. whether we find a new maintainer or we officially announce that it is abandoned.

**Comment by XVilka** [comment]
I think it is better not to repeat Python 3 mistake, otherwise migration off Camlp4 can take decades. In my opinion it is better to do nothing for 4.08, to finally force people to move.

**Comment by ghost** [comment]
I don't disagree, but at the same time it feels like we should be a bit more vocal about such things and announce the plan in advance so that users/packagers/... can be prepared for the change.

I also know from previous discussions that some people care about having a working camlp4 at hand.

So I just want to make sure everybody is on the same page.

For now, releasing a 4.08 compatible version of Camlp4 seems fine to me, especially if it can help getting 4.08 in Debian.

**Comment by pmetzger** [comment]
Maybe we can make the blocking packages in Debian work without camlp4 instead? It will have to happen eventually. @glondu would that help?

**Comment by glondu** [comment]
We have a pretty old version of OCaml (4.05.0) in Debian, and I would like to update it ASAP. But most likely, that won't happen before November. At the moment, there are 62 packages missing in my [test rebuild](https://ocaml.debian.net/transitions/ocaml-4.08.0/) because of a direct dependency to camlp4... and that does not take into account transitive dependencies (in total, there are [193 packages missing](https://ocaml.debian.net/transitions/ocaml-4.08.0/missing.txt) and only 84 built). Having a 4.08-aware version of camlp4 would really help.

What about the future? I've set [as a goal](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933722) to remove camlp4 from Debian. But that will take time. I'm ready to be aggressive about it, but I'm not sure it will be done for bullseye.

**Comment by XVilka** [comment]
https://ocaml.debian.net/transitions/ocaml-4.08.0/missing.txt is unreachable. Can you please attach the file to the issue?

For the packages from https://wiki.debian.org/Teams/OCamlTaskForce/TODO list:
- labgltk3 can be used without camlp4, but requires it for regenerating some files: https://github.com/garrigue/lablgtk/pull/67#issuecomment-506601088, lablgtk2 is being deprecated with the GTK2 itself.
- coccinelle no longer requires camlp4: https://github.com/coccinelle/coccinelle/blob/master/install.txt

**Comment by glondu** [comment]
> https://ocaml.debian.net/transitions/ocaml-4.08.0/missing.txt is unreachable

It is reachable via IPv6 only. If you don't have access, there are plenty of options including tor, miredo or [some other kind of tunnel](https://tunnelbroker.net/).

> Can you please attach the file to the issue?

This is the current version: [missing.txt](https://github.com/ocaml/camlp4/files/3475798/missing.txt). It evolves as I fix things. As you can see, fixing camlp4 would unlock many things, so that's my priority.

> lablgtk2 is being deprecated with the GTK2 itself

I know, but there are still many things depending on lablgtk2 (as you can see in the same file).

> coccinelle no longer requires camlp4

Good to know. And it is being [updated](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932667).

I've updated [the wiki page](https://wiki.debian.org/Teams/OCamlTaskForce/TODO).

**Comment by XVilka** [comment]
Checked the packages list. Most of them do not need camlp4 with the update to the latest version, see for example:
- oasis: https://github.com/ocaml/oasis/blob/master/CHANGES.txt#L199
- camomile: https://github.com/yoriyuki/Camomile/blob/master/camomile.opam (see, no need for camlp4)
- opam - no longer requires cudf, so no need for camlp4 dependency as well.
- utop - no longer requires camlp4 https://github.com/ocaml-community/utop/issues/295
- haxe switched to camlp5 https://github.com/HaxeFoundation/haxe/commit/306840f03c6a3f75e4662288effd5ade853eaf59

And so on. So for a good batch of those the dependency on camlp4 can be safely dropped, on some it is optional but rarely used, so can be dropped too.

Packages like these can be removed completely
- pa-bench
- pa-ounit

They are no longer required for `janest-core-kernel` and others.

See also the discussion about ulex: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/5

**Comment by ghost** [comment]
Thanks @XVilka for looking into this :)

It was unpleasant, but I did manage to switch Camlp4 to 4.08! I'll proceed with the release after lunch.

**Comment by ghost** [comment]
Done: https://github.com/ocaml/opam-repository/pull/14649

**Comment by pmetzger** [comment]
@diml Is this the end of the line? Or will 4.09 also have a camlp4? I figure we should be encouraging migration though, should we not?

**Comment by ghost** [comment]
That's indeed the end of the line and there will be no 4.09 release (as explained on [discuss](https://discuss.ocaml.org/t/the-end-of-camlp4/4216)).

Well, except if someone steps up to take over the project.

I have updated the README to reflect all that.

**Comment by pmetzger** [comment]
Very good. I'll upgrade MacPorts version of camlp4 but I'm going to systematically deprecate all packages that use it, in anticipation of 4.09 arriving. Meanwhile, I hope Debian does something similar. Can we now close this issue?

**Comment by ghost** [comment]
We can close it indeed!
